### ISSUE TITLE
Unable to see anything when running.

### ISSUE THREAD

**Issue by 7ep** [alisabzevari/kotlin-http4k-realworld-example-app#35]
$ javac -version   
javac 11.0.6

$ ./gradlew run
...
[INFO ] o.e.j.s.Server - Started @3084ms
[INFO ] main - Server started on port 9000

curl http://localhost:9000/
(nothing)

Used Chrome: No webpage was found for the web address: http://localhost:9000/
HTTP ERROR 404

Looked with netstat.  A server is listening on 9000:
$ netstat -ant|grep 9000
  TCP    0.0.0.0:9000           0.0.0.0:0              LISTENING       InHost   
  TCP    [::]:9000              [::]:0                 LISTENING       InHost   
  TCP    [::1]:9000             [::1]:59033            TIME_WAIT       InHost   
  TCP    [::1]:9000             [::1]:59034            TIME_WAIT       InHost

**Comment by alisabzevari** [comment]
This project is just providing the api for the example. It doesn't serve the front-end.

**Comment by 7ep** [comment]
ah I see.  Thanks.
